<script setup lang="ts">
import { ref } from "vue";

const props = defineProps<{
  code: string;
}>();

let animationRunning = ref<boolean>(false);

function copyToClipboard(): void {
  navigator.clipboard.writeText(props.code);
  animationRunning.value = !animationRunning.value;
  setTimeout(() => {
    animationRunning.value = !animationRunning.value;
  }, 1000);
}
</script>

<template>
  <div class="code-container">
    <h3>Game Code:</h3>
    <div class="code-and-scissors">
      <p class="code">{{ code }}</p>
      <div
        class="scissors"
        :class="{ heartbeat: animationRunning }"
        title="Copy"
        @click="copyToClipboard()"
      >
        ✂️
      </div>
    </div>
  </div>
</template>

<style scoped>
.code-container {
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
  gap: 0.5rem;
  /* padding-bottom: 2rem;; */
}

.code-and-scissors {
  display: flex;
  justify-content: center;
  align-items: center;
  gap: 0.5rem;
}

.code {
  -webkit-user-select: auto;
  user-select: auto;
  border-radius: 255px 15px 225px 15px/15px 225px 15px 255px;
  border: 3px solid var(--color-text);
  padding: 1rem;
  background-color: #ececec;
  box-shadow: inset 0 0 5px rgb(112, 112, 112);
}
.scissors {
  border-radius: 255px 15px 225px 15px/15px 225px 15px 255px;
  border: 3px solid var(--color-text);
  padding: 1rem;
  background-color: #ececec;
  box-shadow: inset 0 0 5px rgb(112, 112, 112);
  transform: rotate(180deg);
  cursor: pointer;
  position: relative;
  user-select: none;
}

.heartbeat {
  -webkit-animation: heartbeat 1s ease-in-out both;
  animation: heartbeat 1s ease-in-out both;
}

/* ----------------------------------------------
 * Generated by Animista on 2022-11-8 18:17:0
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation heartbeat
 * ----------------------------------------
 */
@-webkit-keyframes heartbeat {
  from {
    -webkit-transform: scale(1) rotate(180deg);
    transform: scale(1) rotate(180deg);
    -webkit-transform-origin: center center;
    transform-origin: center center;
    -webkit-animation-timing-function: ease-out;
    animation-timing-function: ease-out;
  }
  10% {
    -webkit-transform: scale(0.91) rotate(180deg);
    transform: scale(0.91) rotate(180deg);
    -webkit-animation-timing-function: ease-in;
    animation-timing-function: ease-in;
  }
  17% {
    -webkit-transform: scale(0.98) rotate(180deg);
    transform: scale(0.98) rotate(180deg);
    -webkit-animation-timing-function: ease-out;
    animation-timing-function: ease-out;
  }
  33% {
    -webkit-transform: scale(0.87) rotate(180deg);
    transform: scale(0.87) rotate(180deg);
    -webkit-animation-timing-function: ease-in;
    animation-timing-function: ease-in;
  }
  45% {
    -webkit-transform: scale(1) rotate(180deg);
    transform: scale(1) rotate(180deg);
    -webkit-animation-timing-function: ease-out;
    animation-timing-function: ease-out;
  }
}
@keyframes heartbeat {
  from {
    -webkit-transform: scale(1) rotate(180deg);
    transform: scale(1) rotate(180deg);
    -webkit-transform-origin: center center;
    transform-origin: center center;
    -webkit-animation-timing-function: ease-out;
    animation-timing-function: ease-out;
  }
  10% {
    -webkit-transform: scale(0.91) rotate(180deg);
    transform: scale(0.91) rotate(180deg);
    -webkit-animation-timing-function: ease-in;
    animation-timing-function: ease-in;
  }
  17% {
    -webkit-transform: scale(0.98) rotate(180deg);
    transform: scale(0.98) rotate(180deg);
    -webkit-animation-timing-function: ease-out;
    animation-timing-function: ease-out;
  }
  33% {
    -webkit-transform: scale(0.87) rotate(180deg);
    transform: scale(0.87) rotate(180deg);
    -webkit-animation-timing-function: ease-in;
    animation-timing-function: ease-in;
  }
  45% {
    -webkit-transform: scale(1) rotate(180deg);
    transform: scale(1) rotate(180deg);
    -webkit-animation-timing-function: ease-out;
    animation-timing-function: ease-out;
  }
}
</style>
